# Generated by Django 2.0 on 2017-12-14 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='queston_text',
            new_name='question_text',
        ),
    ]
